#ifndef POPUPPERLIB_GLOBAL_H
#define POPUPPERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POPUPPERLIB_LIBRARY)
#  define POPUPPERLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define POPUPPERLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // POPUPPERLIB_GLOBAL_H
